version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: my-coupon
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"