CREATE TABLE MY_COUPON_TICKET_TYPE
(
    ID          SERIAL      NOT NULL PRIMARY KEY,
    NAME        VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT
);

CREATE UNIQUE INDEX MY_COUPON_TICKET_TYPE_ID_UINDEX ON MY_COUPON_TICKET_TYPE (ID);

CREATE TABLE MY_COUPON_TICKET
(
    ID           SERIAL     NOT NULL PRIMARY KEY,
    CODE         VARCHAR(8) NOT NULL,
    TYPE         SERIAL     NOT NULL,
    CREATED_BY   SERIAL     NOT NULL,
    CREATED_TIME TIMESTAMP  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX MY_COUPON_TICKET_ID_UINDEX ON MY_COUPON_TICKET (ID);

CREATE UNIQUE INDEX MY_COUPON_TICKET_CODE_UINDEX ON MY_COUPON_TICKET (CODE);
