CREATE TABLE MY_COUPON_TICKET_TYPE
(
    ID          SERIAL      NOT NULL PRIMARY KEY,
    NAME        VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE MY_COUPON_TICKET
(
    ID           SERIAL      NOT NULL PRIMARY KEY,
    CODE         VARCHAR(8)  NOT NULL,
    TYPE         SERIAL      NOT NULL,
    CREATED_BY   VARCHAR(30) NOT NULL,
    CREATED_TIME TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX MY_COUPON_TICKET_CODE_UINDEX ON MY_COUPON_TICKET (CODE);

ALTER TABLE MY_COUPON_TICKET
    ADD CONSTRAINT MY_COUPON_TICKET_MY_COUPON_TICKET_TYPE_ID_FK
        FOREIGN KEY (TYPE) REFERENCES MY_COUPON_TICKET_TYPE;